# Site settings
title: Reparations People
email: reparationspeople@bangpound.org
description: "A spark and an inventory."
baseurl: ""
url: "http://reparationspeople.com"

# Build settings
markdown: kramdown
permalink: pretty
